### ISSUE TITLE
Fixed decimal and zero operations

### ISSUE THREAD

**Issue by alherdom** [alherdom/macos_calculator#1] opened 2023-10-30 19:19 UTC
Fixed decimal and zero operations

**Comment by Muhammad-Owais-Warsi** [comment] 2023-10-30 19:31
Hey, I wanna solve this issue. Can you please assign this to me.

**Comment by Muhammad-Owais-Warsi** [comment] 2023-10-31 18:08
Finally the issue is fixed i think

**Closed as completed** 2023-10-31 20:30 UTC
